(()=>{'use strict';
const A=StoneTerrainV3,T=A.T,cv=document.querySelector('canvas'),ctx=cv.getContext('2d'),keys=new Set();
function sample(){const width=26,height=19,cells=Array.from({length:height},()=>Array(width).fill(0));const spans={2:[11,14],3:[10,14],4:[8,17],5:[5,19],6:[3,21],7:[2,22],8:[2,23],9:[1,23],10:[1,22],11:[2,21],12:[3,21],13:[5,19],14:[7,17],15:[8,15],16:[8,11],17:[8,10],18:[8,10]};for(const[y,[a,b]]of Object.entries(spans))for(let x=a;x<=b;x++)cells[y][x]=1;cells[2][12]=2;return{width,height,cells,seed:'広間',spawn:{x:12.5*16,y:10.5*16},exit:{x:12.5*16,y:2.5*16},tileSize:16};}
const maps=[...STONE_LIVE_MAPS,sample()];let map,terrain,hero,route=[],stamp=0,roomCenter,last=0,anim=0;
const walk=(x,y)=>[1,2].includes(map.cells[y]?.[x]),W=(x,y)=>walk(Math.floor(x),Math.floor(y));
function biggest(){let best={area:0};for(let y=1;y<map.height-1;y++)for(let x=1;x<map.width-1;x++){if(!walk(x,y))continue;let width=map.width;for(let yy=y;yy<map.height&&width;yy++){let n=0;while(walk(x+n,yy))n++;width=Math.min(width,n);const area=width*(yy-y+1);if(area>best.area)best={area,x:x+width/2,y:y+(yy-y+1)/2};}}return{x:Math.floor(best.x)+.5,y:Math.floor(best.y)+.5};}
function select(i){map=maps[i];terrain=A.create(map);roomCenter=biggest();hero={...roomCenter};route=[];stamp++;render();}
function path(tx,ty){const st=[hero.x|0,hero.y|0],q=[st],prev=new Map([[st.join(),null]]);let end;for(let i=0;i<q.length;i++){const [x,y]=q[i];if(x===tx&&y===ty){end=[x,y];break;}for(const p of [[x+1,y],[x-1,y],[x,y+1],[x,y-1]])if(walk(...p)&&!prev.has(p.join())){prev.set(p.join(),[x,y]);q.push(p);}}if(!end)return[];const out=[];while(end){out.push({x:end[0]+.5,y:end[1]+.5});end=prev.get(end.join());}return out.reverse().slice(1);}
function move(dx,dy){const r=.3,B=(x,y)=>!W(x,y);if(dx&&!B(hero.x+dx+Math.sign(dx)*r,hero.y)&&!B(hero.x+dx+Math.sign(dx)*r,hero.y+r*.7)&&!B(hero.x+dx+Math.sign(dx)*r,hero.y-r*.7))hero.x+=dx;if(dy&&!B(hero.x,hero.y+dy+Math.sign(dy)*r)&&!B(hero.x+r*.7,hero.y+dy+Math.sign(dy)*r)&&!B(hero.x-r*.7,hero.y+dy+Math.sign(dy)*r))hero.y+=dy;}
function camera(){return{x:Math.round(hero.x*T-cv.width/2),y:Math.round(hero.y*T-cv.height*.57)};}
function actor(x,y){x=Math.round(x);y=Math.round(y);const bob=route.length||keys.size?Math.round(Math.sin(anim*13)):0;ctx.fillStyle='#654a35';ctx.fillRect(x-6,y,12,3);ctx.fillRect(x-8,y+1,16,1);y+=bob;const dots=[[-4,-17,8,3,'#252934'],[-6,-14,11,7,'#2f3340'],[-3,-13,6,4,'#bb9467'],[0,-11,3,2,'#d5ac78'],[-5,-8,9,7,'#37414a'],[-7,-5,3,5,'#b88b50'],[4,-6,2,7,'#b88b50'],[-4,-2,3,4,'#292833'],[1,-2,3,4,'#292833'],[-4,-7,8,2,'#9c7444']];for(const[a,b,w,h,col]of dots){ctx.fillStyle=col;ctx.fillRect(x+a,y+b,w,h);}ctx.fillStyle='#bea479';ctx.fillRect(x+7,y-10,1,10);ctx.fillStyle='#d2c3a0';ctx.fillRect(x+7,y-11,2,3);}
function render({marker=true,walls=true}={}){const c=camera(),mode=document.getElementById('layer').value;ctx.imageSmoothingEnabled=false;ctx.fillStyle=A.P.void;ctx.fillRect(0,0,cv.width,cv.height);if(terrain.depth)ctx.drawImage(terrain.depth,-c.x,-c.y);ctx.drawImage(terrain.floor,-c.x,-c.y);if(walls)ctx.drawImage(terrain.walls,-c.x,-c.y);
 if(mode==='analysis'){ctx.fillStyle='#ba8d56';for(let y=0;y<map.height;y++)for(let x=0;x<map.width;x++)if(walk(x,y))ctx.fillRect(x*T-c.x,y*T-c.y,T,T);for(const e of terrain.edges){ctx.fillStyle=e.side==='north'?'#47778b':e.side==='south'?'#77587a':'#647c52';const x=e.x*T-c.x,y=e.y*T-c.y;if(e.side==='north')ctx.fillRect(x,y-12,T,12);if(e.side==='south')ctx.fillRect(x,y+T,T,5);if(e.side==='west')ctx.fillRect(x-4,y,4,T);if(e.side==='east')ctx.fillRect(x+T,y,4,T);}}
 if(mode==='grid'){for(let y=0;y<map.height;y++)for(let x=0;x<map.width;x++){const xx=x*T-c.x,yy=y*T-c.y;if(xx<-T||yy<-T||xx>cv.width||yy>cv.height)continue;ctx.fillStyle=walk(x,y)?'#86a784':'#a07070';ctx.globalAlpha=.15;ctx.fillRect(xx,yy,T,T);ctx.globalAlpha=.3;ctx.fillRect(xx,yy,T,1);ctx.fillRect(xx,yy,1,T);ctx.globalAlpha=1;}}
 if(marker)actor(hero.x*T-c.x,hero.y*T-c.y);
 document.getElementById('status').textContent=`${map.seed==='広間'?'形状サンプル':'本編 seed '+map.seed} · ${map.width}×${map.height} · ${route.length?'移動中':'待機'}`;
}
function narrow(){for(let y=2;y<map.height-2;y++)for(let x=2;x<map.width-2;x++)if(walk(x,y)&&walk(x+1,y)&&!walk(x-1,y)&&!walk(x+2,y)&&walk(x,y-1)&&walk(x,y+1)){hero={x:x+.5,y:y+.5};route=[];return;} }
function tick(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;anim+=dt;let dx=Number(keys.has('d')||keys.has('ArrowRight'))-Number(keys.has('a')||keys.has('ArrowLeft')),dy=Number(keys.has('s')||keys.has('ArrowDown'))-Number(keys.has('w')||keys.has('ArrowUp'));if(dx||dy)route=[];else if(route.length){dx=route[0].x-hero.x;dy=route[0].y-hero.y;if(Math.hypot(dx,dy)<.03){hero={...route.shift()};dx=dy=0;}}const n=Math.hypot(dx,dy);if(n)move(dx/n*Math.min(dt*2.5,n),dy/n*Math.min(dt*2.5,n));render();requestAnimationFrame(tick);}
document.getElementById('map').onchange=e=>select(+e.target.value);document.getElementById('room').onclick=()=>{hero={...roomCenter};route=[];};document.getElementById('narrow').onclick=narrow;document.getElementById('exit').onclick=()=>route=path(map.exit.x/16|0,map.exit.y/16|0);document.getElementById('layer').onchange=e=>{document.getElementById('legend').hidden=e.target.value!=='analysis';render();};document.getElementById('portrait').onclick=e=>{const portrait=cv.width===480;cv.width=portrait?300:480;cv.height=portrait?440:300;document.getElementById('stage').classList.toggle('portrait',portrait);e.target.textContent=portrait?'横画面にする':'縦画面にする';};
window.addEventListener('keydown',e=>{if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();keys.add(e.key);}});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>keys.clear());cv.onpointerdown=e=>{const r=cv.getBoundingClientRect(),c=camera();route=path(Math.floor(((e.clientX-r.left)/r.width*cv.width+c.x)/T),Math.floor(((e.clientY-r.top)/r.height*cv.height+c.y)/T));};
A.ready.then(()=>{select(0);window.STONE_V3={ready:true,render,select,narrow,path,move,walk:W,camera,maps,get map(){return map},get terrain(){return terrain},get hero(){return hero},setHero(p){hero={...p};route=[];}};requestAnimationFrame(tick);}).catch(e=>{document.getElementById('status').textContent=e.message;console.error(e);});
})();
