(()=>{const D=STONE_RD,t=new Image(),p=new Image(),c=document.getElementById('view'),g=c.getContext('2d'),a=document.getElementById('atlas'),ag=a.getContext('2d');let m=D.maps[0],grid=false,collision=false,decor=true,hero={...m.spawn},path=[],keys={},alpha,last=0; t.src='assets/stone-rd-v2/tiles.png';p.src='assets/stone-rd-v2/props.png';
function tile(id,x,y){if(id>=0)g.drawImage(t,id%8*32,(id>>3)*32,32,32,x,y,32,32)}
function point(x,y){if(x<0||y<0||x>=m.w*32||y>=m.h*32)return false;const cx=x/32|0,cy=y/32|0,n=cy*m.w+cx;if(!m.cells[n])return false;const id=m.ground[n],px=x%32|0,py=y%32|0;if(D.bridgeIds.includes(id))return id===D.bridgeIds[0]?px>=8&&px<=23:py>=8&&py<=23;return alpha[(((id>>3)*32+py)*256+id%8*32+px)*4+3]>0;}
function can(x,y){for(let k=0;k<8;k++){const an=k*Math.PI/4;if(!point(x*32+Math.cos(an)*6,y*32+Math.sin(an)*6))return false}return point(x*32,y*32)}
function move(dx,dy){if(can(hero.x+dx,hero.y))hero.x+=dx;if(can(hero.x,hero.y+dy))hero.y+=dy}
function route(target){let start=(hero.y|0)*m.w+(hero.x|0),q=[start],parent=new Map([[start,-1]]);for(let k=0;k<q.length;k++){const n=q[k];if(n===target)break;for(const [dx,dy]of [[0,-1],[1,0],[0,1],[-1,0]]){const x=n%m.w+dx,y=(n/m.w|0)+dy,j=y*m.w+x;if(x<0||x>=m.w||y<0||y>=m.h||parent.has(j)||!m.cells[j])continue;let pass=true;for(let s=0;s<=8;s++)if(!can(n%m.w+.5+dx*s/8,(n/m.w|0)+.5+dy*s/8))pass=false;if(pass){parent.set(j,n);q.push(j)}}}if(!parent.has(target))return[];let arr=[];for(let n=target;n!==-1;n=parent.get(n))arr.push({x:n%m.w+.5,y:(n/m.w|0)+.5});return arr.reverse();}
function draw(){g.imageSmoothingEnabled=false;g.fillStyle='#242332';g.fillRect(0,0,c.width,c.height);for(const layer of [m.cliff,m.ground])layer.forEach((id,n)=>tile(id,n%m.w*32,(n/m.w|0)*32));if(decor)for(const s of m.props)g.drawImage(p,s.id%4*64,(s.id>>2)*64,64,64,s.x,s.y,64,64);if(collision){g.fillStyle='#66dfbc55';m.cells.forEach((v,n)=>{if(v)g.fillRect(n%m.w*32+6,(n/m.w|0)*32+6,20,20)})}if(m.exit){g.strokeStyle='#dcc97b';g.lineWidth=2;g.strokeRect(m.exit.x*32-11,m.exit.y*32-11,22,22)}if(grid){g.strokeStyle='#d5ddd738';g.lineWidth=1;for(let x=0;x<c.width;x+=32){g.beginPath();g.moveTo(x,0);g.lineTo(x,c.height);g.stroke()}for(let y=0;y<c.height;y+=32){g.beginPath();g.moveTo(0,y);g.lineTo(c.width,y);g.stroke()}}g.fillStyle='#161826';g.fillRect(Math.round(hero.x*32)-7,Math.round(hero.y*32)-10,14,15);g.fillStyle='#a9e5df';g.fillRect(Math.round(hero.x*32)-5,Math.round(hero.y*32)-8,10,10);g.fillStyle='#f0efd6';g.fillRect(Math.round(hero.x*32)-3,Math.round(hero.y*32)-6,6,3)}
function step(now){const dt=Math.min((now-last)/1000,.04);last=now;let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0);if(dx||dy){path=[];const l=Math.hypot(dx,dy);move(dx/l*dt*3,dy/l*dt*3)}else if(path.length){let p=path[0],x=p.x-hero.x,y=p.y-hero.y,d=Math.hypot(x,y),v=Math.min(d,dt*3);if(d<.02)path.shift();else move(x/d*v,y/d*v)}draw();requestAnimationFrame(step)}
window.RD_TEST={get map(){return m},can,point,route,move,get hero(){return hero},setHero(x,y){hero={x,y}},draw};window.ready=Promise.all([t.decode(),p.decode()]).then(()=>{a.width=t.width;a.height=t.height;ag.drawImage(t,0,0);alpha=ag.getImageData(0,0,a.width,a.height).data;c.width=m.w*32;c.height=m.h*32;draw();requestAnimationFrame(step)});
for(const id of ['grid','collision','decor'])document.getElementById(id).onclick=()=>{if(id==='grid')grid=!grid;if(id==='collision')collision=!collision;if(id==='decor')decor=!decor;draw()};document.getElementById('reset').onclick=()=>{hero={...m.spawn};path=[]};document.getElementById('route').onclick=()=>{if(m.exit)path=route((m.exit.y|0)*m.w+(m.exit.x|0))};document.getElementById('map').onchange=e=>{m=D.maps[+e.target.value];hero={...m.spawn};path=[];c.width=m.w*32;c.height=m.h*32;draw()};window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){keys[e.key]=true;e.preventDefault()}});window.addEventListener('keyup',e=>keys[e.key]=false);window.addEventListener('blur',()=>keys={});c.onclick=e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*m.w|0,y=(e.clientY-r.top)/r.height*m.h|0;path=route(y*m.w+x);document.getElementById('status').textContent=`セル ${x},${y} / タイル ${m.ground[y*m.w+x]+1} / 接続マスク ${m.masks[y*m.w+x]} / ${path.length?'経路あり':'経路なし'}`};})();
