(()=>{const D=CAVE_LAYERS,M=D.map,c=document.getElementById('view'),g=c.getContext('2d'),atlas=new Image();atlas.src='assets/stone-rd-v3/atlas.png';let hero={...M.spawn},keys={},path=[],last=0,opt={walls:true,moss:true,props:true,glow:true,grid:false};g.imageSmoothingEnabled=false;
function cell(x,y){return x>=0&&y>=0&&x<M.w&&y<M.h?M.cells[y*M.w+x]:0}
function can(x,y){const r=.22;for(const[dx,dy]of [[-r,-r],[r,-r],[-r,r],[r,r]])if(!cell(Math.floor(x+dx),Math.floor(y+dy)))return false;return true}
function move(dx,dy){if(can(hero.x+dx,hero.y))hero.x+=dx;if(can(hero.x,hero.y+dy))hero.y+=dy}
function route(x,y){const target=(y|0)*M.w+(x|0),start=(hero.y|0)*M.w+(hero.x|0);if(!cell(x|0,y|0))return[];const q=[start],parent=new Map([[start,-1]]);for(let k=0;k<q.length;k++){const n=q[k];if(n===target)break;for(const[dx,dy]of [[0,-1],[1,0],[0,1],[-1,0]]){let xx=n%M.w+dx,yy=(n/M.w|0)+dy,j=yy*M.w+xx;if(cell(xx,yy)&&!parent.has(j)){parent.set(j,n);q.push(j)}}}if(!parent.has(target))return[];let out=[];for(let n=target;n!==-1;n=parent.get(n))out.push({x:n%M.w+.5,y:(n/M.w|0)+.5});return out.reverse()}
function part(id,x,y,bottom=false){let p=D.parts[id];g.drawImage(atlas,p.x,p.y,p.w,p.h,Math.round(x),Math.round(y-(bottom?p.h:0)),p.w,p.h)}
function player(){const x=Math.round(hero.x*16),y=Math.round(hero.y*16);g.fillStyle='#0e152a';g.fillRect(x-4,y-11,8,12);g.fillStyle='#dce9d0';g.fillRect(x-2,y-10,4,4);g.fillStyle='#82bdc6';g.fillRect(x-3,y-6,6,5);g.fillStyle='#aacebd';g.fillRect(x-3,y-1,2,2);g.fillRect(x+1,y-1,2,2)}
function draw(){g.imageSmoothingEnabled=false;g.globalAlpha=1;g.fillStyle=D.background;g.fillRect(0,0,c.width,c.height);M.ground.forEach((id,n)=>{if(id>=0)part(id,n%M.w*16,(n/M.w|0)*16)});if(opt.moss)for(const p of M.moss)part(p.id,p.x,p.y);if(opt.glow){g.globalCompositeOperation='screen';for(const p of M.props.filter(p=>p.id===24)){const x=p.x+16,y=p.y-7;const gr=g.createRadialGradient(x,y,1,x,y,28);gr.addColorStop(0,'#28766b88');gr.addColorStop(1,'#10262d00');g.fillStyle=gr;g.fillRect(x-28,y-28,56,56)}g.globalCompositeOperation='source-over';}
const sorted=[...(opt.walls?M.walls:[]),...(opt.props?M.props:[]),{player:true,sort:hero.y*16}].sort((a,b)=>a.sort-b.sort||Number(!!a.player)-Number(!!b.player));for(const p of sorted){if(p.player)player();else {part(p.id,p.x,p.y,true);if(p.cap!==null&&p.cap!==undefined)part(p.cap,p.x,p.y-24,true)}}
if(opt.grid){M.cells.forEach((v,n)=>{g.strokeStyle=v?'#70c9b250':'#99586d30';g.strokeRect(n%M.w*16,(n/M.w|0)*16,16,16)});g.fillStyle='#7ce3c280';g.fillRect(hero.x*16-3,hero.y*16-3,6,6)}g.strokeStyle='#b2bf8d';g.strokeRect(M.exit.x*16-4,M.exit.y*16-4,8,8);}
function tick(t){let dt=Math.min((t-last)/1000,.05);last=t;let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0);if(dx||dy){path=[];let len=Math.hypot(dx,dy);move(dx/len*dt*3,dy/len*dt*3)}else if(path.length){let p=path[0],dx=p.x-hero.x,dy=p.y-hero.y,d=Math.hypot(dx,dy);if(d<.02)path.shift();else{let dist=Math.min(d,dt*3);move(dx/d*dist,dy/d*dist)}}draw();requestAnimationFrame(tick)}
window.ready=atlas.decode().then(()=>{draw();requestAnimationFrame(tick)});window.CAVE_TEST={M,D,can,move,route,draw,opt,get hero(){return hero},setHero(x,y){hero={x,y};path=[]},setOption(k,v){opt[k]=v},findOcclusion(){for(const w of M.walls){const x=w.cell%M.w,y=w.cell/M.w|0;if(w.face==='foreground'&&cell(x,y-1))return{x:x+.5,y:y-.35,wall:w}}}};
for(const id of Object.keys(opt))document.getElementById(id).onchange=e=>{opt[id]=e.target.checked;draw()};document.getElementById('home').onclick=()=>{hero={...M.spawn};path=[]};document.getElementById('exit').onclick=()=>path=route(M.exit.x,M.exit.y);document.getElementById('occlude').onclick=()=>{const p=CAVE_TEST.findOcclusion();hero={x:p.x,y:p.y};path=[];document.getElementById('status').textContent='人物を手前の壁の裏に配置しました。「壁」をOFFにすると位置を確認できます。'};
window.addEventListener('keydown',e=>{if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){keys[e.key]=true;e.preventDefault()}});window.addEventListener('keyup',e=>keys[e.key]=false);window.addEventListener('blur',()=>keys={});for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;e.preventDefault()};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false;}c.onclick=e=>{let r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*M.w,y=(e.clientY-r.top)/r.height*M.h;path=route(x,y);document.getElementById('status').textContent=path.length?'指定した床へ移動中':'壁・移動不可の領域です'};
})();
